### ISSUE TITLE
Refinar colisiones

### ISSUE THREAD

**Issue by Frodo2412** [Frodo2412/playing-with-open-gl#47]
Actualmente el bicho cuando se mueve contra algo lo que hace es no moverse. Como nuestra velocidad de movimiento es bastante grande, esto esta generando que el bicho quede lejos de los bloques.

Habriq que arreglar esto para que quede de forma que las dos bounding box se esten tocando. El metodo que hay que modificar es 

```cpp
void player::handle_collision(game_object* other)
{
    position_ -= speed_;
    speed_ = vector3::zero();
}
```

Creo que algo que se puede hacer es simplemente ir acortando la velocidad a la mitad y hacer la llamada recursivamente.

**Comment by Frodo2412** [comment]
Aca hay un bosquejo de algo de codigo que estuve probando (tiene un comportamiento raro):

```cpp
void player::handle_collision(game_object* other)
{
    const auto mov = speed_.normalize();
    do
    {
        position_ -= mov;
    }
    while (check_collision(other));
    speed_ = vector3::zero();
}
```

**Comment by matiasencion** [comment]
intenté pero no pude
