### ISSUE TITLE
Luces titilan

### ISSUE THREAD

**Issue by matiasencion** [Frodo2412/playing-with-open-gl#67]
Ahora la posicion real del personaje es la speed, pero cada vez que te moves esa velocidad va a (0,0,0) y ahi se mueve la luz al (0,0,0) y parece que titila, debe ser eso

**Comment by Frodo2412** [comment]
Esto sigue pasando? Yo no lo estoy experimentando

**Comment by stg-27** [comment]
Se habrá solucionado ahora con el arreglo que hiciste del 0.1? Porque no me está sucediendo
